name: logging_to_logcat_example
description: Demonstrates how to use the logging_to_logcat plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0-1.0.dev <4.0.0"

dependencies:
  logcat_monitor : ^0.0.6
  logging: ^1.1.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5


  flutter:
    sdk: flutter

  logging_to_logcat:
    # When depending on this package from a real application you should use:
    #   logging_to_logcat: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true